language: node_js
node_js:
- stable
script:
- bash scripts/build.sh
after_success:
- bash scripts/gendocs.sh
- bash scripts/genexamples.sh
- bash scripts/genfull.sh
env:
  global:
  - ENCRYPTION_LABEL: a34ff6591ac8
notifications:
  slack:
    secure: X5Ke+WV3Emh5/JNKfjt73oAMCk+Ok8We54Xm8UqONs8gPdXS9NGuKLX50Tn0Kpw9mQVSeZ7/A+4J7fzYNp18vDFt+4QtugPIFs9h6xcKZe9TXMERoaUcjdaDh7+f4cyjPkAyABVSzwiWlDZ49Ke4t/Bftr0b9w7rg9d6aSewLjk=
    on_success: never
    on_failure: always